email: false

sudo: false

language: python

matrix:
  include:
    - os: linux
      python: 3.5
    - os: osx
      language: generic

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install -r requirements-ci.txt
  - pip install aiodns uvloop

script:
  - pip wheel .
